# Generated by Django 5.1.1 on 2025-01-02 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='head_of_department',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='citizen',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='service',
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.citizen')),
            ],
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='citizen',
            field=models.ManyToManyField(related_name='service_requests', to='app.citizen'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='service',
            field=models.ManyToManyField(related_name='requests', to='app.service'),
        ),
    ]
