# Generated by Django 5.1.1 on 2025-01-31 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='department',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='citizen',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='service',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='citizen',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='citizen',
            name='registration_date',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='status',
        ),
        migrations.RemoveField(
            model_name='service',
            name='fee',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_name',
        ),
        migrations.AddField(
            model_name='service',
            name='name',
            field=models.CharField(default='dog control', max_length=200),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='first_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='last_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(null=True)),
                ('rating', models.PositiveIntegerField(null=True)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='app.citizen')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='app.service')),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='ServiceRequest',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
