# Generated by Django 5.1.1 on 2025-01-31 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_citizen_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citizen',
            name='user',
        ),
        migrations.AddField(
            model_name='complaint',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
